###############################################
##
## ONCODRIVER
##
## Provide the expected key:values
## Note that several keys/values can be defined
## 
###############################################


## Define here how to extract the different information from the VCF file

vcf:
  tag: 'ANN'
  sep: '&'
  vaf: 'AF'
  depth: 'DP'
  alt_depth: 'AD'
  annot_info: 1
  gene_id: 3
  transcript_id : 6
  cancer_db:
    - 'ICGC'
    - 'CancerHotspots'
    - 'COSMIC'
  polym_db:
    gnomAD:
      - AF

cnv:
  gene_id: 10
  class: 8
  start: 1
  end: 2


## Define the variant selection algorithm
select:

  ## SNVs

  ## Oncogenes/TSG/Both/Unknown
  ## Misense and Frameshift variants in driver genes and known in databases
  - var_type: 'snv'
    gene_type: 'oncogene|tsg|both|unknown'
    var_classes:
      - missense_variant
      - conservative_inframe_deletion
      - conservative_inframe_insertion
      - disruptive_inframe_deletion
      - disruptive_inframe_insertion
    is_hotspot: true

  - var_type: 'snv'
    gene_id: 'TERT'
    var_classes:
      - upstream_gene_variant

  ## TSG/Both/Unknown
  ## Stop, Splice, Frameshift variants in driver genes, even if not known in databases
  - var_type: 'snv'
    gene_type: 'tsg|both|unknown'
    var_classes:
      - stop_gained
      - splice_donor_variant
      - splice_acceptor_variant
      - frameshift_variant

  ## Copy Number Variants
  
  - var_type: 'cnv'
    gene_type: 'oncogene|both|unknown|'
    var_classes:
      - AMP
    maxsize: 10000000
    copy: 5

  - var_type: 'cnv'
    gene_type: 'tsg|both|unknown'
    var_classes:
      - DEL

